### ISSUE TITLE
Finishing Up

### ISSUE THREAD

**Issue by bobtat** [RobertTatoian/FaceMapping#10]
@WarrenGM I think that we're pretty much finished is there anything else you can think of? I already provided JavaDoc comments for the entire program.

**Comment by warrengm** [comment]
I can't really think of anything. Time to submit it? :smile:

**Comment by bobtat** [comment]
I think it's time! How should we do it? It sounds like a stupid question, but the OpenCV libraries that we're using are build for Windows... I think he might have the Mac versions but I'm not sure.

**Comment by warrengm** [comment]
Actually, I just thought that maybe we should move the debug mode window outside of 3d? I think it would improve usability if we showed the frame parallel to the screen when someone enters debug mode.

On that note. Maybe '`' isn't the best key for debug mode. Maybe backspace?

I also noticed one part where the indentation is off.

I can commit those changes.

**Comment by bobtat** [comment]
Ok commit those changes, I'm not sure if Processing can handle the backspace though.

As for the debug mode I think since we're using Processing 3D everything in the windows has to be 3D, even if it's a '2D' plane. Thoughts?

**Comment by warrengm** [comment]
The backspace character is '\b' so we can use that to detect it.

For the plane, I realized that if we draw the images after popMatrix, we will be back to the original pixel coordinates so we can draw them directly to the screen.

**Comment by bobtat** [comment]
Actually come to think of it if we pushed the matrix, then used resetMatrix, then poped again we wouldn't need to move anything.

**Comment by warrengm** [comment]
Yea, that would work too.

So, is everything done now?

**Comment by bobtat** [comment]
Yeah I think so, what do you think would be the best way to submit it?

**Comment by warrengm** [comment]
What about a zip with a link to the Github repo if they re interested?

**Comment by warrengm** [comment]
Without the .git folder

**Comment by bobtat** [comment]
That's fine, but only concern is if he can't get it running.

**Comment by bobtat** [comment]
I was thinking including a compiled application, but I can't get Proclipsing to give me on that works.

**Comment by warrengm** [comment]
I've always just submitted the source. Maybe we can post a screenshot of it running with the face detection? He teaches a computer vision class so he should know how to get OpenCV running.

**Comment by warrengm** [comment]
Do you know how create a .jar?

**Comment by bobtat** [comment]
Not entirely, well for an application using just the core library yes.

**Comment by bobtat** [comment]
I guess he should be able to figure it out

**Comment by warrengm** [comment]
I think so. I don't think there is a better way to do it. Maybe we can include screesnhots of it running?

**Comment by bobtat** [comment]
I just packaged it up to submit and I included the link to this github page in the manual, but we could do that.

**Comment by bobtat** [comment]
I'll also send the package to you

**Comment by warrengm** [comment]
Hold off for a second, I noticed one minor thing with the texture

**Comment by bobtat** [comment]
Ok, I just sent you the file to review everything

**Comment by bobtat** [comment]
Hey we might want to remove the blue rectangles around the eyes

**Comment by bobtat** [comment]
I'll do it, unless you wanted to keep them

**Comment by warrengm** [comment]
I thought about removing the blue rectangles around the eyes, but without them it's hard to know if both eyes are being detected.

**Comment by bobtat** [comment]
Ok we can leave them in then.

**Comment by bobtat** [comment]
Are we ready to submit?

**Comment by warrengm** [comment]
I think so

**Comment by bobtat** [comment]
OK, I'm sending you a link to the revised copy.

**Comment by bobtat** [comment]
Let me know when you get it.

**Comment by warrengm** [comment]
got it

**Comment by bobtat** [comment]
OK, If you want to look it over let me know if its good to submit, otherwise I'll do it now.

**Comment by warrengm** [comment]
It's time ..

**Comment by bobtat** [comment]
Alright I'll do it now

**Comment by bobtat** [comment]
It's done, the semester's officially over! :smiley:

**Comment by warrengm** [comment]
Finally, just two days before christmas. At least there're no classes for a month.

Have a great Christmas!

**Comment by bobtat** [comment]
Haha you too! See you next semester!
