### ISSUE TITLE
Adding bugs, enhacements or questions?

### ISSUE THREAD

**Issue by bobtat** [RobertTatoian/FaceMapping#2]
Hey Warren, since we only have until 5 tomorrow to complete the project I think it'd be a good idea to add any of the above to this issue tracker. This way we don't forget anything!

**Comment by warrengm** [comment]
Great idea! I'll post anything I come up with as an issue. We should probably have smaller commits and push more frequently so we each have the most up-to-date code as possible.

**Comment by bobtat** [comment]
Yes I agree, I'm trying to wrap up this CSF final as soon as I can, but I'll be working on this most of the night as well.
