### ISSUE TITLE
Scale the world coordinate system

### ISSUE THREAD

**Issue by warrengm** [RobertTatoian/FaceMapping#5]
I noticed that the world coordinates aren't scaled from pixel coordinates. I was thinking about making the unit of measurement being inches so the height of the window would be about 10 inches since that's roughly the size of a face when looking at the webcam input.

Also, the y-axis is currently pointing down, not up.

What do you think Robert?

**Comment by bobtat** [comment]
Yes, I meant to do that last night when I was centering the 3D scene. So for your scaling one pixel would equal 10 inches? For a world size that seems reasonable.
