### ISSUE TITLE
What's Left?

### ISSUE THREAD

**Issue by bobtat** [RobertTatoian/FaceMapping#9]
@WarrenGM I still have to implement the scaling, but everything else seems to be finished. If you can think of anything to add else submit an new issue. Otherwise we can start to clean up and comment the code.

**Comment by warrengm** [comment]
I don't think that there is much. We need to make sure that it is thoroughly commented and has a consistent formatting style. I tried to follow how you indent and place curly brace but I think that there are some parts where my IDE reformatted the code differently.

Also, I started playing around with the camera trying to get a FPS-like effect. So far moving the mouse works nicely but the pressing the WASD keys doesn't move the camera in the direction its facing (instead it moves the camera along the axes). I'll push what I have for you to try.

**Comment by bobtat** [comment]
OK I can export the settings I'm using in Eclipse to format the code, if your IDE can import them? Otherwise I can just handle the formatting.

**Comment by warrengm** [comment]
I'm not sure if intellij can import settings from eclipse. Do you have a shortcut to autoformat your code?

**Comment by bobtat** [comment]
What do you mean by shortcut?

**Comment by warrengm** [comment]
In intellij I can select some code and then press "ctrl-alt-L" and it will automatically change the curly braces, indentation, etc, to format the code according to my settings

**Comment by bobtat** [comment]
Yes, that sounds like what I do in Eclipse. I have an option to export my settings, but I'm not sure if IntelliJ can import them?

**Comment by warrengm** [comment]
I looked it up, there is a way to do it. I'll import your code style if you email it to me

**Comment by bobtat** [comment]
OK, I'll get them to you; also I just formatted and cleaned everything... take a look
